// <auto-generated />
using System;
using FitLife.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitLife.Infrastructure.Migrations
{
    [DbContext(typeof(FitLifeDbContext))]
    [Migration("20251120174818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitLife.Domain.Entities.Habito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Habitos");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.RegistroAlimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Calorias")
                        .HasColumnType("int");

                    b.Property<double>("Carboidratos")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<double>("Gorduras")
                        .HasColumnType("float");

                    b.Property<double>("Proteinas")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosAlimentacao");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.RegistroHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HabitoId");

                    b.ToTable("RegistrosHabito");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTreino")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Treinos");

                    b.HasDiscriminator<string>("TipoTreino").HasValue("Treino");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FitLife.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.TreinoCardio", b =>
                {
                    b.HasBaseType("FitLife.Domain.Entities.Treino");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("float");

                    b.Property<int>("FrequenciaCardiacaMedia")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Cardio");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.TreinoMusculacao", b =>
                {
                    b.HasBaseType("FitLife.Domain.Entities.Treino");

                    b.Property<double>("CargaKg")
                        .HasColumnType("float");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Musculacao");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.Habito", b =>
                {
                    b.HasOne("FitLife.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Habitos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.RegistroAlimentacao", b =>
                {
                    b.HasOne("FitLife.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RegistrosAlimentacao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.RegistroHabito", b =>
                {
                    b.HasOne("FitLife.Domain.Entities.Habito", "Habito")
                        .WithMany("Registros")
                        .HasForeignKey("HabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habito");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.Treino", b =>
                {
                    b.HasOne("FitLife.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Treinos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.Habito", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("FitLife.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Habitos");

                    b.Navigation("RegistrosAlimentacao");

                    b.Navigation("Treinos");
                });
#pragma warning restore 612, 618
        }
    }
}
